### ISSUE TITLE
package bmic not found (in a non-standard prefix install)

### ISSUE THREAD

**Issue by teuben** [csdms/bmi#69] opened 2020-06-29 14:20 UTC
I first installed bmic:

mkdir _build && cd _build
cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/opt
make install

and then the example-C in the same fashion:

mkdir _build && cd _build
cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/opt

when I get "No package 'bmic' found"

Is there a flag in cmake one gives to say that bmic is installed in a non-standard place, or did I not follow all install instructions.

https://github.com/openjournals/joss-reviews/issues/2317

**Comment by mdpiper** [comment] 2020-06-29 15:18
Hmm, pkg-config should locate the library. I'll disable it to see if I can reproduce this result.

(There may be some delay since I'm on vacation this week.)

**Comment by teuben** [comment] 2020-06-30 13:46
I should add that bmi-cxx has not too surprisingly the same issue with not finding bmicxx.

The fortran and python installed and tested fine (but see #70)

**Comment by mcflugen** [comment] 2020-07-01 17:31
@teuben Thank you so much for looking at this!

To help *pkg-config* find things installed in non-standard locations, you can set the *PKG_CONFIG_PATH* environment variable. For example, the following works for me.

Install the *bmi-c* package,
```bash
$ mkdir _build && cd _build  # In bmi-c
$ cmake ../ -DCMAKE_INSTALL_PREFIX=/tmp/opt
$ make install
```
Install the *bmi-example-c* example,
```bash
$ mkdir _build && cd _build  # In bmi-example-c
$ export PKG_CONFIG_PATH=/tmp/opt/lib/pkgconfig
$ cmake ../ -DCMAKE_INSTALL_PREFIX=/tmp/opt
$ make install
```
Run the example,
```bash
$ /tmp/opt/bin/run_bmiheatc testing/config.txt  # In bmi-example-c
$ ls bmiheatc.out
bmiheatc.out
```
The first ten line of the output file,
```
Configuration file = testing/config.txt
Initializing... done
The 2D Heat Equation
variable = plate_surface__temperature
rank = 2
shape = 5 x 6

Time = 0.000000
0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
0.00e+00 2.24e+00 2.24e+00 5.43e+00 -1.46e+00 0.00e+00
```

**Comment by mdpiper** [comment] 2020-07-06 22:39
Hi @teuben -- in the PRs listed above, I've updated the READMEs in the bmi-example-c and bmi-example-cxx repos to try to clarify how to install to a nonstandard location. Please let me know what you think. If they address this issue satisfactorily, I'll close the issue and merge the PRs.

**Comment by teuben** [comment] 2020-07-14 13:03
yes, go ahead and merge. They work for me.

**Closed** 2020-07-14 15:23 UTC
Labels: documentation
